[WIP] Meter component
PublicisSapient/enable-a11y pull request #116
Opened 2024-06-05 14:49 UTC by akr3081

Creates a new page for the meter component

2024-06-10 16:26 UTC, akr3081 commented on css/meter.css
> +  width: 70%;
This solution using css [attribute selectors](https://developer.mozilla.org/en-US/docs/Web/CSS/Attribute_selectors) does work, but it has a few limitations. If there is a better means of handling this, please let me know.

1. Meter will only show a visual differences every 10%. This is because the value is treated as a string and not a number. Therefore there is no greater than or less than functionality.
2. Support for meter low, high, and optimum fields will need to be defined in the css.

2024-06-10 16:31 UTC, akr3081 commented
Tests are all passing locally, however, I am seeing the following error which causes the Run Automated tests step to fail.

`error: Bad value “meter” for attribute “role” on element “div”.`

To my knowledge, this is a valid role as of [Aria 1.2](https://www.w3.org/TR/wai-aria-1.2/#meter)

2024-06-10 18:05 UTC, alisonhall commented on css/meter.css
> +  width: 70%;
Would using JS to add a class based on the value, and then styling based on those classes? Using JS would also allow us to us less than and greater than functionality.

2024-06-10 18:31 UTC, alisonhall commented
> Tests are all passing locally, however, I am seeing the following error which causes the Run Automated tests step to fail.
> 
> `error: Bad value “meter” for attribute “role” on element “div”.`
> 
> To my knowledge, this is a valid role as of [Aria 1.2](https://www.w3.org/TR/wai-aria-1.2/#meter)

I checked out your branch on my computer and ran the tests, and I can see the same error in the v.Nu tests that was reported in the automated tests online. Could different versions of Java produce different results? (FYI, I'm on a Mac running Java version 1.8.0.221).

2024-06-11 14:41 UTC, zoltan-dulac requested changes
I absolutely love how you were able to go through and add everything needed to create a new page on your own.  I guess the unit tests for the social media needs have worked as well, since you got a poster image there.

Let me know if you have any questions regarding feedback.  As per the cross-browser styling comment: I want you to have fun with styling <meter>.  Do something fancy if you can.  Take a look at demos on the web to inspire you.  This is the great thing about working on Enable -- you can do research and suggest to others how to do things they don't have time to do but you have.  Savour that (it's one of the main reasons why I love working on this project).

2024-06-11 14:41 UTC, zoltan-dulac commented on content/body/meter.php
> +<?php includeStats(["isForNewBuilds" => true]); ?>
Before we put badges on the page, we should definitely ensure we test with screen readers to understand the difference between how things are read between the two versions and among different screen readers.

We should test:

- Voiceover/Safari (iOS and OSX)
- NVDA/Firefox (Windows)
- Talkback and Chrome (Android)

Please note what is the differences between the native and ARIA version on these platforms.  If you need assistance with Windows, either I or another dev on the project should be able to help here.

2024-06-11 14:41 UTC, zoltan-dulac commented on css/meter.css
> +  width: 70%;
Ahhh .. how I wish `attr()` worked within `calc()`!   It does work inside of `content`, though -- you may want to consider putting the value visually on the meter so users can read precisely what the value is.

I would prefer not using JS as much as possible -- just to see how far we style this without JS.

2024-06-11 14:41 UTC, zoltan-dulac commented on css/meter.css
> +.meter-container {
There are cross browser differences in how your examples are rendered.  This is an opportunity to do some research to see how you can style these to ensure  we can make <meter> look best in a cross-browser way.

This may be a good place to start: https://stackoverflow.com/questions/8094835/how-to-style-html5-meter-tag

Please consider using a LESS mixin so developers can style them easily.

2024-06-11 21:11 UTC, alisonhall commented on content/body/meter.php
> +    <label id="disk-c-meter" aria-hidden="true">Disk C:</label>
If you are using these labels for the meters, you don't want to have the `aria-hidden` attribute on any of them.

2024-06-11 21:11 UTC, alisonhall commented on css/meter.css
> -.meter-container p {
Is this change to the meter.css file for this component? If so, all style changes need to be done in the `.less` files instead, not the `.css` files. The `.css` files are automatically generated based on the `.less` files, and therefore any manual changes to them are overwritten.

2024-06-12 16:43 UTC, akr3081 commented on content/body/meter.php
> +    <label id="disk-c-meter" aria-hidden="true">Disk C:</label>
I added the `aria-hidden` attribute as the screen reader was reading the label and meter as separate items. It would announce "Disk C, Label" and then "20%, Disk C, level indicator".

With this, the screen reader just announces the meter element as "20%, Disk C, level indicator". Is it preferred to be announced separately?

2024-06-12 16:44 UTC, akr3081 commented on css/meter.css
> -.meter-container p {
Ah gotcha, I was unaware we were using LESS for this. I'll switch it over!

2024-06-12 18:11 UTC, alisonhall commented on content/body/meter.php
> +    <label id="disk-c-meter" aria-hidden="true">Disk C:</label>
Can you tie the label to the meter component by using the `for` attribute in the way that other form elements do? If you can use that attribute, then you shouldn't need the `aria-hidden` attribute and the screen reader wouldn't read out the label separately.

2024-06-12 19:11 UTC, akr3081 commented on css/meter.css
> +.meter-container {
Set up LESS file with mixins and variables for easier usage

2024-06-12 19:28 UTC, akr3081 commented on content/body/meter.php
> +    <label id="disk-c-meter" aria-hidden="true">Disk C:</label>
I had attempted to use the `for`/`id` pattern I've seen elsewhere, however, it still seems to read both out separately. I agree that using `aria-hidden` is not ideal and am definitely open to changing it if there is another way.

2024-06-13 20:32 UTC, akr3081 commented on content/body/meter.php
> +<?php includeStats(["isForNewBuilds" => true]); ?>
I have verified both examples are read the same across all platforms. The only one I am personally unable to replicate is voiceover with iOS as I don't have access to an iPhone.

2024-06-14 17:25 UTC, alisonhall commented on content/body/meter.php
> +    <label id="disk-c-meter" aria-hidden="true">Disk C:</label>
Does having the `label` element wrap around the `meter` element work? Ie. `<label>Disk C:<meter></meter></label>`

2024-06-14 17:57 UTC, alisonhall commented on content/body/meter.php
> +  Should a case arise where there HTML5 meter component is not accessible for a given browser, the following can be used as an alternative.
_nit_: 
```suggestion
  Should a case arise where the HTML5 meter component is not accessible for a given browser, the following can be used as an alternative.
```

2024-06-14 17:57 UTC, alisonhall commented on content/body/meter.php
> +  This page provides examples of both HTML and aria based solutions for creating accessible meter components.
_nit_
```suggestion
  This page provides examples of both HTML and ARIA based solutions for creating accessible meter components.
```

2024-06-14 17:57 UTC, alisonhall commented on content/body/meter.php
> +  If you are using VNU for validation, there is a <a href="https://github.com/validator/validator/issues/1380">known issue</a> with <code>role="meter"</code>.
_nit_
```suggestion
  If you are using v.Nu for validation, there is a <a href="https://github.com/validator/validator/issues/1380">known issue</a> with <code>role="meter"</code>.
```

Also, should we start the line with "Hint: "?

2024-06-14 17:57 UTC, alisonhall commented on content/body/meter.php
> +          "highlight": "aria-label",
Instead of just the "aria-label" code, the whole "aria-labelledby" and the label's "id" tags should be highlighted. Additionally, the instructions should talk about the "aria-labelledby" instead of "aria-label".

2024-06-14 17:57 UTC, alisonhall commented on content/body/meter.php
> +            "highlight": "%OPENCLOSECONTENTTAG%p",
This highlight code doesn't seem to actually select anything. Should it be for `aria-hidden="true"` instead?

2024-06-14 17:57 UTC, alisonhall commented on content/body/meter.php
> +          "highlight": "aria-label",
Like the previous code example, you aren't actually using `aria-label` anymore, only `aria-labelledby` and the associated `id` attributes. This should probably be reflected in this instructions step.

2024-06-14 17:57 UTC, alisonhall commented on content/body/meter.php
> +          "highlight": "%OPENCLOSECONTENTTAG%p",
This highlight code doesn't seem to actually select anything. Should it be for aria-hidden="true" instead?

2024-06-14 17:57 UTC, alisonhall commented on content/body/meter.php
> +          "highlight": "%JS% meter.init",
This highlight code doesn't seem to actually select anything. Should it be for the setAttribute lines instead?

2024-06-14 17:57 UTC, alisonhall commented on content/body/meter.php
> +          "highlight": "%CSS% meter-css~",
This highlight code doesn't seem to actually select anything. Should anything be highlighted?

2024-06-14 17:57 UTC, alisonhall commented on js/test/meter.test.js
> +    beforeAll(async () => {});
If you aren't including anything in the `beforeAll` section, then it probably doesn't need to be included.

2024-06-14 17:57 UTC, alisonhall commented on js/test/meter.test.js
> +describe('Meter Tests', () => {
Along with your HTML5 test, you also need to test your ARIA code example.

2024-06-14 18:59 UTC, akr3081 commented on content/body/meter.php
> +    <label id="disk-c-meter" aria-hidden="true">Disk C:</label>
Tried this as well, still no luck.

2024-06-14 19:39 UTC, alisonhall commented on js/test/meter.test.js
> +        expect(domInfo.meters[5].fill).toBe('--meter-percentage: 60%');
For well written unit tests, you should be able to see the features of the code just by reading the unit test names. Can we separate the HTML5 and the ARIA tests into separate `it` unit test blocks to make it clearer? It also makes the unit tests more portable and readable in the case additional examples are added to the page.

2024-06-14 19:52 UTC, alisonhall submitted a review, later dismissed

2024-06-25 19:24 UTC, akr3081 commented on content/body/meter.php
> +    <label id="disk-c-meter-html5" aria-hidden="true">Disk C:</label>
Refer to this thread on this issue
https://github.com/PublicisSapient/enable-a11y/pull/116#discussion_r1640231049

2024-06-25 19:24 UTC, akr3081 commented on content/body/meter.php
> +
Refer to this thread on this issue
https://github.com/PublicisSapient/enable-a11y/pull/116#discussion_r1640231049

2024-06-25 19:25 UTC, akr3081 commented on content/body/meter.php
> +      aria-labelledby="disk-e-meter-aria"
Refer to this thread on this issue
https://github.com/PublicisSapient/enable-a11y/pull/116#discussion_r1640231049

2024-06-25 21:33 UTC, akr3081 commented on content/body/meter.php
> +<?php includeStats(["isForNewBuilds" => true]); ?>
Connected with @ocjadan and it seems there is a minor discrepancy with the two examples (only occurring on iOS). 

The HTML5 example reads each meter value as optimal/suboptimal/critical. The ARIA example reads the actual value of each meter (similar to how this is done on chrome/firefox).

If anyone is aware of a way to resolve this, please let me know. Otherwise I can add a note about this specific scenario to the page.

2024-06-28 19:08 UTC, akr3081 commented on content/body/meter.php
> +<?php includeStats(["isForNewBuilds" => true]); ?>
Resolved using `aria-valuetext`. All platforms are now announced consistently.

2024-06-28 21:12 UTC, akr3081 commented on bin/checkHTML.sh
> +	$AXE --exit --verbose --exclude ".enable-logo__text" --exclude "#announcements-carousel,.enable-custom-meter" $AXE_UNDELAYED_URLS
Added axe exclusion for `.enable-custom-meter` element as it was incorrectly getting an `aria-allowed-attr` error. Obviously this is not the ideal solution so if anyone is aware of another way of handling this, please let me know.

Usage of `aria-valuetext` is documented here - https://www.w3.org/WAI/ARIA/apg/practices/range-related-properties/#usingaria-valuetext

2024-07-02 18:39 UTC, akr3081 commented on bin/checkHTML.sh
> +	$AXE --exit --verbose --exclude ".enable-logo__text" --exclude "#announcements-carousel,.enable-custom-meter" $AXE_UNDELAYED_URLS
Resolved by bumping axe-core to v4.9.1

2024-07-03 16:47 UTC, zoltan-dulac requested changes

2024-07-03 16:47 UTC, zoltan-dulac commented on content/body/meter.php
> +    <label id="disk-c-meter-html5" aria-hidden="true">Disk C:</label>
Let's discuss this in the next call ... just want to make sure I understand the reasoning (I think I know what the issue is, but I want to make sure).

2024-07-03 16:47 UTC, zoltan-dulac commented on js/modules/meter.js
> + * meter.js - Adds full support for meter component without use of HTML5 meter
I am assuming this is for ARIA role="meter", correct?

If so, let's say this is a helper script for ARIA role="meter" and explain what it implements.  The description here is a little confusing for me.

2024-07-03 16:47 UTC, zoltan-dulac commented on js/test/meter.test.js
> +        expect(domInfo.meters[2].valuetext).toBe('60%');
I see what you are trying to do here.

I want to make sure every meter has the right HTML attributes set -- I don't want to test they are exactly the values they are on the page currently.  If we change the values, the tests should still pass.

e.g. valuetext should have a percentage value (but I don't want to dictate what that value is), the meter-state should be appropriate for the value, etc.

2024-07-11 13:31 UTC, merged