removing : and space between asterik
PublicisSapient/enable-a11y pull request #119
Opened 2024-06-05 19:52 UTC by Neha-Singla

2024-06-06 18:49 UTC, alisonhall commented
I noticed that capitalization of the inline error message isn't consistent (ie. "enter your phone number", "enter a valid email address", "Phone number invalid"). Maybe we should capitalize the beginning of each of these statements?

2024-06-06 18:51 UTC, alisonhall commented on js/demos/custom-form-example.js
> +                email_js: 'Error: enter a valid email address',
Should we capitalize the 'Enter' word to make it consistent?

2024-06-06 19:34 UTC, zoltan-dulac requested changes
Please make alison's change and then I'll approve.

2024-06-06 19:51 UTC, Neha-Singla commented on js/demos/custom-form-example.js
> +                email_js: 'Error: enter a valid email address',
done

2024-06-07 15:17 UTC, alisonhall approved these changes

2024-06-10 18:13 UTC, alisonhall approved these changes

2024-06-10 18:28 UTC, zoltan-dulac approved these changes

2024-06-10 18:39 UTC, alisonhall approved these changes

2024-06-10 18:44 UTC, merged

2024-06-11 19:26 UTC, alisonhall commented on css/form-error.css
> +  content: "*";
@Neha-Singla , I just noticed that this change was made in the `.css` file, and not the `.less` file. This means that whenever the styles are recompiled, this change is overwritten. All style changes need to be done in the `.less` files.

2024-06-12 15:30 UTC, Neha-Singla commented on css/form-error.css
> +  content: "*";
https://github.com/PublicisSapient/enable-a11y/pull/137
Please approve this.