feat: test cases for the Tab component
PublicisSapient/enable-a11y pull request #130
Opened 2024-06-07 16:38 UTC by mahesh0618

2024-06-07 19:21 UTC, zoltan-dulac commented
This is a good start.  I would like the following added:

1) Do the selector fix outlined above.
2) I would also like to add in the unit test that the active tab always has `aria-selected="true"`.
3) Ensure the DOM has the right structure.  Take a look at the code walk-through on the [Enable Tabs page](https://www.useragentman.com/enable/tabs.php).  Steps #5-#9 in that walk-through will tell you what you should test for. (I should have outlined that to you before starting work that you should go through the code walk-throughs).





Let me know when this is done and I'll approve (I do want to run on my local to double check when I am done, but it looks like it works as it should.

2024-06-10 14:27 UTC, mahesh0618 commented
@zoltan-dulac Feedback has been incorporated, please validate.

2024-06-11 13:48 UTC, mahesh0618 commented on js/test/tabs.test.js
> +                ];
the feedback has been incorporated

2024-06-11 16:23 UTC, zoltan-dulac requested changes

2024-06-11 16:23 UTC, zoltan-dulac commented on js/test/tabs.test.js
> +});
One thing I did forget: we should have a unit test where we test JS off on the page.  If you test the current page with JS off, it should behave like a bunch of anchors to content and work (albeit differently).  


I think you can do it using this:


```

const page = await browser.newPage()
await page.setJavaScriptEnabled(false)

```

Take a look at [this stack overflow page ](https://stackoverflow.com/questions/51897899/how-to-stop-all-js-scripts-in-puppeteer) for more info.


I have never done this before, but I think this should work, and it should be tested.

2024-06-11 16:23 UTC, zoltan-dulac commented on js/test/tabs.test.js
> +        expect(domInfo.focusDefaultTab).toBe(true);
There should be a test that:

1) Focus one interactive element before the tab component.
2) Press the TAB key.
3) See which Tab is accessed.   Is it the selected one?
4) Tab out of it.
5) Tab backwards into it.  Is it is selected tab again?

You should also test whether the instructions appear with keyboard only.

2024-06-11 16:24 UTC, zoltan-dulac commented
Hi Mahesh! Good job so far.  Just want a few more changes.  After those are done, I think we can merge.

2024-06-12 15:51 UTC, mahesh0618 commented on js/test/tabs.test.js
> +                }
updated to use ```contains```

2024-06-12 15:52 UTC, mahesh0618 commented on js/test/tabs.test.js
> +});
added a test case to check JS disabled scenarios

2024-06-12 15:54 UTC, mahesh0618 commented on js/test/tabs.test.js
> +        expect(domInfo.focusDefaultTab).toBe(true);
added a test case to check the outlined scenarios

2024-06-13 13:36 UTC, zoltan-dulac approved these changes

2024-06-13 14:16 UTC, merged