[Issue# 49] - Fix the Grammar / Spelling Issues on all sub sections of Content Page Navigation Item
PublicisSapient/enable-a11y pull request #138
Opened 2024-06-12 17:56 UTC by akshaypanchal

- Used Grammarly app for grammar check. (Default version)
- All sub sections of the Content Page Navigation Item are checked.

2024-06-13 13:50 UTC, zoltan-dulac requested changes

2024-06-13 13:50 UTC, zoltan-dulac commented on content/body/video-content.php
> +  <dd>A text version of speech and other important audio content in a video, allows it to be accessible to people who
Please change this copy (I didn't realize how awkward it is until I reread it):

Original text: 

A text version of speech and other important audio content in a video, allows it to be accessible to people who can't hear all of the audio.

to:

Text that appears during the playing of a video, usually placed at the bottom of the viewing area, that displays what people in the video are saying in realtime.  Captions also describe other important audio content in a video, like sound effects in the background.

2024-06-13 13:50 UTC, zoltan-dulac commented on content/body/video-content.php
> +  <dd>An extra audio track with spoken commentary helps users with visual disabilities perceive content that is
Please change:

An extra audio track with spoken commentary helps users with visual disabilities perceive content

to:

An extra audio track with spoken commentary helps blind and partially-sighted users perceive content

2024-06-13 19:46 UTC, alisonhall commented on content/body/animated-gif-with-pause-button.php
> +        "All the examples here are useful for new and existing work where you want to pause animated GIFs most straightforwardly",
I agree with Zoltan that it is easier to read in the original way.

2024-06-20 13:49 UTC, alisonhall commented on content/body/heading.php
> +  Screen-reader users also use headings to skim through a web page quickly and are used by screen-reader users as a table of contents. For example, using NVDA, this is done via the Elements List, and
I think we have been trying to be consistent in terms of how we spell "screen reader" throughout the site.

```suggestion
  Screen reader users also use headings to skim through a web page quickly and are used by screen-reader users as a table of contents. For example, using NVDA, this is done via the Elements List, and for Voiceover, this is done via The Rotor.  The following video shows how screen reader users use these tools.
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/img.php
> +  Many developers use SVG Sprites so they can put all their SVG icons in one place and have their <code>svg</code> tags point to a shape in the sprite inside their HTML code.  This can make your webp
```suggestion
  Many developers use SVG Sprites so they can put all their SVG icons in one place and have their <code>svg</code> tags point to a shape in the sprite inside their HTML code.  This can make your webpage more efficient when there are a lot of icons on a page, as described in the article <a href="https://cloudfour.com/thinks/svg-icon-stress-test/">Which SVG technique performs best for way too many icons?</a> by <a href="https://tylersticka.com/">Tyler Sticka</a>.  Here, we show you how to embed them in an accessible way like the other SVG examples on this page.
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/progress.php
> +            a bit of noise and sets the aria-live level appropriately. If the user is not going to be doing anything
I think the original text makes more sense, since it's not the noise that is setting the aria-live level:

```suggestion
            a bit of noise, and set the aria-live level appropriately. If the user is not going to be doing anything
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/reflow.php
> +  A common design problem on many e-commerce sites is PLPs (product listing pages). Consider the screenshot below
I think the original text made more sense:

```suggestion
  A common design problem on many e-commerce sites is on PLPs (product listing pages). Consider the screenshot below
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/screen-reader-only-text.php
> +    <li>Text read in your screen reader's reading mode (i.e. using it to read the page, not for reading out the interactive elements that have focus), screen reader only text is guaranteed to work.
I think that this makes the last sentence more clear:

```suggestion
    <li>Text read in your screen reader's reading mode (i.e. using it to read the page, not for reading out the interactive elements that have focus), screen reader only text is guaranteed to work.  ARIA labels might not be read in the reading mode of your screen reader.</li>
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/screen-reader-only-text.php
> +  <li>If you are using a content management system (CMS), you should remember that you must make screen reader only text and any aria-labels authorable.  I advise always having a default value for th
We should make "screen reader-only" consistent within this sentence:

```suggestion
  <li>If you are using a content management system (CMS), you should remember that you must make screen reader only text and any aria-labels authorable.  I advise always having a default value for these items in case someone forgets to author them, or better still, make them mandatory for authors to fill out in the CMS (since screen reader-only text and aria-labels are sometimes forgotten by content authors). <strong>This is really important when you have a multilingual website, since hard-coding screen reader-only text and aria-labels will result in that text may not be understood by users who don't know the language that hard-coded text is written in</strong>.</li>
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/screen-reader-only-text.php
> +  <li>If you are using a third party like <a href="https://www.motionpoint.com">MotionPoint</a> to do your translation, you will want to make sure their service logs the translation of screen reader
I think that "third-party" is still correct:

```suggestion
  <li>If you are using a third-party like <a href="https://www.motionpoint.com">MotionPoint</a> to do your translation, you will want to make sure their service logs the translation of screen reader only text, aria-labels, and image alt text.</li>
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/table.php
> +<p><strong>Many web developers who use <code>&lt;table&gt;</code> markup, however, don't know there are some additional codes they need to make them accessible</strong> (even <a href="https://css-tri
Should it be the following, since "codes" isn't something that exists? And CSS Tricks is the name of a website.

```suggestion
<p><strong>Many web developers who use <code>&lt;table&gt;</code> markup, however, don't know there is some additional code they need to make them accessible</strong> (even <a href="https://css-tricks.com/complete-guide-table-element/">the CSS Tricks' so called "Complete" Guide to the Table Element</a> doesn't cover these items adequately, in my opinion):</p>
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/table.php
> +    way less complicated UI, and if marked up correctly, is accessible via screen readers and keyboard.
I think the following is what was trying to be conveyed in the original text:

```suggestion
    way less complicated UI, and if marked up correctly, is still accessible via screen readers and keyboard.
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/video-content.php
> +    script the actors in the video used to know what is going on in the story that they are about to act in. A transcript
Are we sure this is the correct tense change?

2024-06-20 13:49 UTC, alisonhall commented on content/body/video-content.php
> +  What many don't know is that they need audio descriptions to be WCAG AA compliant.</p>
It's not the audio descriptions themselves that are to be WCAG AA compliant:

```suggestion
  What many don't know is that they need audio descriptions in order to be WCAG AA compliant.</p>
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/video-content.php
> +<h2>Should I use auto-generated captions For My Videos?</h2>
Either capitalize everything in the header, or nothing. And it should be consistent throughout the page.

```suggestion
<h2>Should I Use Auto-Generated Captions For My Videos?</h2>
```

2024-06-20 13:49 UTC, alisonhall commented on content/body/video-content.php
> +  proper transcript; it contains descriptions of what is happening visually that are not given by the spoken text in the
Are we sure this is the correct tense change?

2024-06-20 13:49 UTC, alisonhall commented on templates/includes/npm.php
> +    You can import the module using requirements like this:
We are talking about the actual `require` code. So maybe it should be like the following?

```suggestion
    You can import the module using <code>require</code> like this:
```

2024-06-21 18:02 UTC, closed without merging