Enable-8 create a better character counter widget
PublicisSapient/enable-a11y pull request #144
Opened 2024-06-17 19:41 UTC by ocjadan

2024-06-20 14:43 UTC, alisonhall commented
This page currently has the following text for the character count section:

> The character counter uses a JavaScript library to implement it. Below is the HTML markup needed for it to work, as well as instructions on how to load the library in your own projects.

Are we still using a JavaScript library? If so, I think we should mention which library it is. If not, then this text needs to be changed.

2024-06-20 14:43 UTC, alisonhall commented on content/body/textbox.php
> +            data-read-count-key="Escape"
I wasn't told the instructions about the Escape key. And the escape key didn't seem to do anything for me. Are you sure this part is working?

2024-06-20 14:43 UTC, alisonhall commented on content/body/textbox.php
> +      "label": "Set hasCharacterCount for the textarea element.",
Should we use `data-has-character-count` instead of `hasCharacterCount`, since that's what's in the code?

```suggestion
      "label": "Set the custom data-has-character-count attribute for the textarea element.",
```

2024-06-20 14:43 UTC, alisonhall commented on content/body/textbox.php
> +      "notes": "There's no need to explicitly provide a value of \"true\"."
If we don't need to provide the "true" value, should we then not include it in the code itself?

2024-06-20 14:43 UTC, alisonhall commented on content/body/textbox.php
> +      "notes": "The default is the 'Escape' key. For information regarding which keypress events are recognized visit https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_val
Does it work if we make the link an actual `<link>` element so that users can click on it?

2024-06-20 14:43 UTC, alisonhall commented on content/body/textbox.php
> +      "label": "Optional: Change the amount of available characters left before the screen reader starts announcing after each keypress.",
This line of text seems to almost be too long for the dropdown to display on most screens. Can we shorten it and put the full text in the "notes" section?

2024-06-20 14:43 UTC, alisonhall commented on js/modules/enable-character-count.js
> +    const instructionsToInterpolate = instructions ?? defaultInstructions;
Since we don't use `defaultInstructions` anywhere else, should we just do the following?

```suggestion
    const instructionsToInterpolate = instructions ??'Press ${keyToPress} to find out how many more characters are allowed.';
```

2024-06-20 14:43 UTC, alisonhall commented on js/modules/enable-character-count.js
>      }
(Optional) Technically, this can be slightly simplified to the following:

```suggestion
    if (readCountKey) {
      return keyPressed === readCountKey;
    }
    return keyPressed === defaultReadCharacterCountKey;
```

2024-06-20 15:22 UTC, ocjadan commented on content/body/textbox.php
> +            data-read-count-key="Escape"
I was testing on Safari with VoiceOver—thanks for reminding me I should test on FireFox and Chrome. What are you using, Alison?

2024-06-20 15:22 UTC, ocjadan commented
> This page currently has the following text for the character count section:
> 
> > The character counter uses a JavaScript library to implement it. Below is the HTML markup needed for it to work, as well as instructions on how to load the library in your own projects.
> 
> Are we still using a JavaScript library? If so, I think we should mention which library it is. If not, then this text needs to be changed.

2024-06-20 15:49 UTC, ocjadan commented on content/body/textbox.php
> +      "notes": "There's no need to explicitly provide a value of \"true\"."
Sounds like it's better to remove this note and explicitly provide "true" to avoid confusion. I'll make the change.

2024-06-20 16:15 UTC, ocjadan commented on content/body/textbox.php
> +      "notes": "The default is the 'Escape' key. For information regarding which keypress events are recognized visit https://developer.mozilla.org/en-US/docs/Web/API/UI_Events/Keyboard_event_key_val
Yes, much cleaner now.

2024-06-20 16:49 UTC, ocjadan commented on content/body/textbox.php
> +            data-read-count-key="Escape"
Tests:

1. Safari - Voiceover:  Escape key works ✅.
2. Firefox - VoiceOver: Escape key works ✅.
3. Chrome - VoiceOver: Escape key only works when there's a change to the text. Subsequent keypresses do not announce until there's again a change to the text. ❓

Have you experienced this before, Alison?

2024-06-21 19:39 UTC, alisonhall commented on content/body/textbox.php
> +            data-read-count-key="Escape"
Hi @ocjadan , as mentioned during the standup today, I'm not familiar with the differences in screen reader experiences between browsers. We should probably bring this up with @zoltan-dulac. He will likely know more.

2024-06-25 18:53 UTC, alisonhall commented on content/body/textbox.php
> +            data-read-count-key="Escape"
@ocjadan are you able to do any investigation on why this functionality is not working on Chrome compared to other browsers? Is there a work-around in order to make it also work on Chrome?

2024-06-25 19:12 UTC, zoltan-dulac commented on js/modules/enable-character-count.js
> +  const defaultReadCharacterCountKey = 'Escape';
We forgot "use strict"  in the initial script.  Can you do this here and make any modifications, if needed?

2024-06-26 21:11 UTC, ocjadan commented on content/body/textbox.php
> +            data-read-count-key="Escape"
Hi @alisonhall  and @zoltan-dulac , I have made changes such that when a key is pressed down the aria-live region is cleared and when the key is lifted up the aria-live region is re-populated.

Unfortunately, Chrome still does not announce the character count if there has been no change in the text. _I've played around with holding down the key, waiting, then lifting up; as well as increasing the timeout delay._

Looking around the web, there is this general consensus for aria-live regions: _"Chrome, along with other browsers, often requires a change in the text content of a live region to trigger these announcements."_

Is it okay to chalk this down to Chrome having different behavior?

2024-06-26 21:11 UTC, ocjadan commented on content/body/textbox.php
> +            data-character-count-text="Character Count: ${numChars} out of ${maxLength}. ${charsRemaining} characters remaining."></textarea>
Completed, please have a look when you've got time!

2024-06-26 21:17 UTC, ocjadan commented on content/body/textbox.php
> +            data-read-count-key="Escape"
I've also tried the following scenarios without success for Chrome:

1. Try replacing the outer container <div> with <p> to see if Chrome will read it repeatedly on key press. ❌ Did not work.
2. Try deleting the entire <p> and re-inserting. ❌ Did not work.
3. Try increasing timeout to 300ms-1000ms. ❌ Did not work.

2024-07-03 16:34 UTC, zoltan-dulac commented on js/modules/enable-character-count.js
> +  function setUpEventsFor(target) {
You have some functions ending with `For` and others without.  

Let's be consistent.  Remove the `For`.  I think most devs would understand.

2024-07-04 15:47 UTC, ocjadan commented
Hi @zoltan-dulac , I've decided on going with adding/removing an exclamation to the end of the text to force Chrome to "see a difference" on each key press.

For example:
1. 1st key press = "Character Count: 10/100."
2. 2nd key press = "Character Count: 10/100.!" 
3. 3rd key press = "Character Count: 10/100."

This approach works for Safari, Firefox and Chrome with VoiceOver on Mac.

2024-07-04 15:58 UTC, ocjadan commented
If you were wondering, here are other methods I've tried:

Did not work ❌:

1. Adding or removing a whitespace at the end of the announcement text on each key press.
2. Doing everything in the KeyUp event (removal, timeout, populate).

**aria-atomic**

3. "true" without removing the \<p\> element.
4. "true" while also deleting the \<p\> element and appending a new \<p\> element to live region each time.

**aria-relevant**

5. Set to 'text'.
6. Set to 'additions'.
7. Set to 'additions removals' -> ⚠️ works but VoiceOver "double-speaks" — it tries to read out the removal and immediately is interrupted by the addition. Even with no timeout there is a noticeable interruption. As a result, don't think this is acceptable.

**aria-live**

8. Set to 'assertive'.

**aria-busy**

9. Setting to "true" on keydown and then "false" on key up (before or after .textContent).

**Other Methods**

10. Force re-building between \<p\> and \<div\>.
11. Force re-building between \<p\> and \<span\>.
12. Repeating 9 and 10 with 'aria-atomic' as well.
13. Using only \<div\> without the inner \<p\> element and changing .textContent for that single \<div\>.
14. Removing the element around the text on every other keypress.
15. Adding a brand-new \<p\> element within the ARIA live region on every key press.
15. Remove the inner \<p\> element, use .textContent for \<div\> and appending to it on every key press. This sort of works but VoiceOver will repeat the entire string, which has the previous counts as well. ❌ Not acceptable.

2024-07-09 16:44 UTC, zoltan-dulac requested changes

2024-07-09 16:44 UTC, zoltan-dulac commented on less/textbox.less
> +.enable-character-count {
Can we have a default style for the enable-character-counter and have it is part of the NPM package?

2024-07-09 18:44 UTC, ocjadan commented on less/textbox.less
> +.enable-character-count {
Hey @zoltan-dulac ,

Trying to understand your request a bit more, the \<div\< element that this style is applied to is programmatically added below the \<textarea\> — the \<div\> does not exist before the JavaScript is ran. As a result, I was wondering if you meant:

1. Programmatically and explicitly setting the style, e.g. `div.setAttribute("style", "border-color:#FFFFFF;");`?
2. enable-character-count.js should import less/textbox.less and apply the style programmatically?

2024-07-11 12:44 UTC, zoltan-dulac approved these changes

2024-07-11 12:51 UTC, merged