Add additional terms for components
PublicisSapient/enable-a11y pull request #149
Opened 2024-06-21 16:05 UTC by Umasankar430

2024-06-21 19:17 UTC, alisonhall commented on templates/data/meta-info.json
> +    "desc": "A control with no native HTML5 equivalent, switches/Toggles have become popular recently in web and mobile applications, but many are inaccessible to screen reader and keyboard-only user
We should be consistent with casing:

```suggestion
    "desc": "A control with no native HTML5 equivalent, switches/toggles have become popular recently in web and mobile applications, but many are inaccessible to screen reader and keyboard-only users.  Here's how to code them correctly."
```

2024-06-21 19:17 UTC, alisonhall commented on content/body/switch.php
> +      the switch/toggle role</a>.  The switch/toggle reports the checked state as "on" or "off" in VoiceOver
There is no such thing as an ARIA toggle role, which is why it just said "switch" in this sentence.

```suggestion
      the switchrole</a>.  The switch/toggle reports the checked state as "on" or "off" in VoiceOver
```

2024-06-21 19:17 UTC, alisonhall commented on content/body/switch.php
> +  <code>switch/toggle</code> role in JavaScript.
There is no such thing as an ARIA toggle role, which is why it just said "switch" in this sentence.

```suggestion
  <code>switch</code> role in JavaScript.
```

2024-06-21 19:17 UTC, alisonhall commented on content/body/switch.php
> +  Like <a href="tabs.php">tablists.php</a>, switches/Toggles do not have a native HTML5 tag, so we implement custom code using
We need to be consistent with casing:

```suggestion
  Like <a href="tabs.php">tablists.php</a>, switches/toggles do not have a native HTML5 tag, so we implement custom code using
```

2024-06-21 19:19 UTC, alisonhall commented
@Umasankar430 , I still only see page changes around the Switch/Toggle. Have you been able to look at other terms?

2024-06-24 17:45 UTC, zoltan-dulac commented on content/body/switch.php
> +  Many developers will implement switches/toggles using the <code>&lt;input type="checkbox"&gt;</code>, since the native HTML5
I would like to ensure we use the word `switch` more than toggle.  Toggle should be used in the title for SEO purposes.  In the first paragraph it should be referred to once:


> A switch *(also known as a toggle)* is like a checkbox, in that is designed to be an input control that has a binary value

I would not refer to toggle elsewhere in the code.  We should be promoting the name that is used as an ARIA role wherever possible as default.

2024-06-24 17:45 UTC, zoltan-dulac commented on templates/data/meta-info.json
> +    "title": "Accessible Drawers",
Please rename "Accessible Drawers (a.k.a. Accordions or Expandos)".

2024-06-26 14:16 UTC, alisonhall commented on templates/data/meta-info.json
> +    "title": "Accessible Drawers (a.k.a. Accordions or Expandos)",
Where did the "Dropdown" name go?

2024-07-03 16:08 UTC, zoltan-dulac requested changes

2024-07-03 16:09 UTC, zoltan-dulac commented on templates/data/meta-info.json
> +    "title": "Number Input Spinner",
I agree.  Let's change back.  Make the heading for that page consistent as well.

2024-07-04 17:00 UTC, alisonhall approved these changes

2024-07-05 18:06 UTC, merged