[WIP] Tooltip update
PublicisSapient/enable-a11y pull request #157
Opened 2024-07-02 17:29 UTC by lunarias

2024-07-03 12:59 UTC, zoltan-dulac commented on less/tooltip.less
> +        height: 3;
This is invalid CSS.

2024-07-09 16:13 UTC, zoltan-dulac requested changes

2024-07-09 16:13 UTC, zoltan-dulac commented on less/tooltip.less
> +    &.tp:before {
Let's use BEM here.  Also, let's spell out the whole word here:

&--top
&--bottom

It makes it easier to read.

2024-07-09 16:13 UTC, zoltan-dulac commented on less/tooltip.less
> +.tooltipButtonCommon {
Since the rest of enable is using kabob case (e.g. tooltip-button-common), please use that instead of camel case (e.g. tooltipButtonCommon).

All of these classes also begin with the `.tooltip` prefix (as I would expect them to be).  Use the next `&` in LESS to make this simpler:


```
.tooltip {

  ...

  &-button-hover {
     ...
  }

  &-icon-button {
     ...
  }

 // etc.
}
```

2024-07-09 16:13 UTC, zoltan-dulac commented on less/tooltip.less
> +}
Let's put mixins on the top of the file.  Also put comments telling what are the mixins.

2024-07-09 16:13 UTC, zoltan-dulac commented on less/tooltip.less
> +    font-size: 12px; /* adjust font size as needed */
Fonts should be rems using `font-size: 12/@px`.

2024-07-10 19:45 UTC, lunarias commented on less/tooltip.less
> +.tooltipButtonCommon {
Done

2024-07-10 19:46 UTC, lunarias commented on less/tooltip.less
> +}
Done. Added external mixins (outside of .tooltip class)

2024-07-10 19:46 UTC, lunarias commented on less/tooltip.less
> +    font-size: 12px; /* adjust font size as needed */
Done

2024-07-10 19:46 UTC, lunarias commented on less/tooltip.less
> +    &.tp:before {
Done

2024-07-29 20:28 UTC, zoltan-dulac requested changes

2024-07-29 20:28 UTC, zoltan-dulac commented on js/modules/es4/tooltip.js
> +        body.addEventListener('keydown', this.onKeydown);
Can we do this onkeyup?  It is a little better for accessibility.

2024-07-29 20:28 UTC, zoltan-dulac commented on js/modules/es4/tooltip.js
> +        if (e.which === 27) {
We should make all events consistent.  If we use e.key above, we should use it here as well (I know this is existing code ... but we should do this to be consistent).

2024-07-29 20:28 UTC, zoltan-dulac commented on js/modules/es4/tooltip.js
> +        if (tooltipTarget.tagName.toLowerCase() === 'button' && tabbedIn) {
We shouldn't transform the tagName if we don't need to.  It's extra processing.

2024-07-29 20:28 UTC, zoltan-dulac commented on js/modules/es4/tooltip.js
> +        tooltipStyle.top = 'calc(' + (tooltipTargetRect.bottom + window.scrollY) + 'px + 1em)';
Let's use template strings here. It's more readable, and is more performant.

(I know you just moved existing code, but let's improve it while doing that).

2024-07-29 20:28 UTC, zoltan-dulac commented on js/modules/es4/tooltip.js
> +        tooltipStyle.left = (tooltipTargetRect.left + window.pageXOffset) + 'px';
template strings here too.

2024-07-29 20:28 UTC, zoltan-dulac commented on less/tooltip.less
> +/* Main tooltip */
The above should be encorporated into the BEM below.

2024-08-15 21:31 UTC, lunarias commented on js/modules/es4/tooltip.js
> +        body.addEventListener('keydown', this.onKeydown);
Due to the requirement of having the tooltip not initially show up when you tab into it, oneKeyup does not work since the logic can only be performed when the tab key is released after the initial tab-in. This is why onKeydown was used to check for tabbing behaviour specifically.

2024-08-16 15:15 UTC, lunarias commented on js/modules/es4/tooltip.js
> +        if (e.which === 27) {
Done, using "e.key" with checked values sets as constants

2024-08-16 15:15 UTC, lunarias commented on js/modules/es4/tooltip.js
> +        if (tooltipTarget.tagName.toLowerCase() === 'button' && tabbedIn) {
Done

2024-08-16 15:15 UTC, lunarias commented on js/modules/es4/tooltip.js
> +        tooltipStyle.top = 'calc(' + (tooltipTargetRect.bottom + window.scrollY) + 'px + 1em)';
Done

2024-08-16 15:15 UTC, lunarias commented on js/modules/es4/tooltip.js
> +        tooltipStyle.left = (tooltipTargetRect.left + window.pageXOffset) + 'px';
Done

2024-08-16 15:15 UTC, lunarias commented on less/tooltip.less
> +/* Main tooltip */
Done

2024-09-09 17:15 UTC, zoltan-dulac commented
Hi there.  Just a few things that would make this a bit easier to use:

1) When the user clicks on the tooltip button, you set the button's `aria-describedby` as `tooltip`.  Instead of that, let's do the following:
   - On page load, set the `aria-live="assertive"` to  `<div id="tootip">`.   
   - If you do the first step, when the user clicks on a tooltip button, screen readers will announce the tooptip text that appears.
   - Please remove the `aria-describedby` logic.  It shouldn't be there if the tooltip is activated on click (it should remain for the onfocus variation).

2) You have two different types of tooltips -- one on focus and one on click.    I would like to keep the onfocus variation, but I'd like to have it in a separate section, with a separate explanation about how it works.

3) Let's change the copy with references of "I" to "We".  The "I" implies I wrote it (and I did when I first posted this page, but there are a number of changes you have made that make this better).

4) Put your name on the acknowledgements page. :-)

2024-09-09 17:16 UTC, zoltan-dulac requested changes
Please read my last comment in the conversation tab -- there are a few things I'd like to do here before we sign off on this.

2024-10-08 18:09 UTC, lunarias commented
@zoltan-dulac please do not merge yet, need to fix unaffected files that have been changed not related to tooltip

2024-10-09 15:49 UTC, zoltan-dulac requested changes

2024-10-17 14:58 UTC, merged