WIP: unit test cases for combobox
PublicisSapient/enable-a11y pull request #160
Opened 2024-07-03 15:35 UTC by Neha-Singla

https://github.com/PublicisSapient/enable-a11y/issues/120

2024-07-09 15:57 UTC, zoltan-dulac requested changes

2024-07-09 15:57 UTC, zoltan-dulac commented on js/test/combobox.test.js
> +    it('HTML5 Native combobox is not completely keyboard accessible', async () => {
I thought I mentioned this, but it probably forgot: you don't need to do unit testing on the native  HTML5 versions of components.  Only the custom ARIA versions.

I'll mention this in the next meeting.  This should be true for all unit testing.

2024-07-09 15:57 UTC, zoltan-dulac commented on js/test/combobox.test.js
> +        await page.waitForSelector('#aria-fruit');
I'd like you to test all ARIA comboboxes at the same time (there are two).

2024-07-09 15:57 UTC, zoltan-dulac commented on js/test/combobox.test.js
> +        };
Testing the specific values of `role` and `ariaAutocomplete` is good.  

For the others, I want to make sure:

`ariaDescribedby` is set and that the id exists on the page.
`ariaExpanded` is set to an appropriate value 
`ariaOwns` is set and that the id exists on the page and that its a proper list.

2024-07-09 15:57 UTC, zoltan-dulac commented on js/test/combobox.test.js
> +});
Other things you should test:

1. Does the "Clear" button work.
2. Does the "Escape" key work
3. If I type in a string, does the number of items get populated correctly?  How about the screen reader aria-live announcement?
4. Can we check the markup for the combobox with categories?

2024-07-10 04:24 UTC, Neha-Singla commented on js/test/combobox.test.js
> +    it('HTML5 Native combobox is not completely keyboard accessible', async () => {
done

2024-07-10 04:25 UTC, Neha-Singla commented on js/test/combobox.test.js
> +        await page.waitForSelector('#aria-fruit');
i am testing the all three combo boxes. need to check on this

2024-07-10 04:25 UTC, Neha-Singla commented on js/test/combobox.test.js
> +        };
ariaDescribedby is set and that the id exists on the page.--done

2024-07-16 15:48 UTC, Neha-Singla commented on js/test/combobox.test.js
> +        await page.waitForSelector('#aria-fruit');
done

2024-07-16 15:50 UTC, Neha-Singla commented on js/test/combobox.test.js
> +});
done

2024-07-24 19:30 UTC, zoltan-dulac commented on js/test/combobox.test.js
> +        expect(domInfo.focusedElementType).toBe('reset');
This is a good test, but I would also like another test where you type in a half completed word (e.g. "Ap") and choose one of the autocomplete suggestions (e.g. "Apple").  

Also you should test to see how many autocomplete suggestions it does suggest and make sure it is accurate.

2024-07-25 05:17 UTC, Neha-Singla commented on js/test/combobox.test.js
> +        expect(domInfo.focusedElementType).toBe('reset');
done

2024-08-15 19:48 UTC, zoltan-dulac approved these changes

2024-08-15 20:35 UTC, merged