(#153) Enforce using rems/ems in stylesheets
PublicisSapient/enable-a11y pull request #204
Opened 2024-08-15 16:46 UTC by seyilonge-ps

2024-08-15 17:12 UTC, zoltan-dulac requested changes

2024-08-15 17:12 UTC, zoltan-dulac commented on less/bookmarklets.less
> +    margin: 1.25rem 0;
I was hoping that we would only have to change the font-size attributes from `px` to `rem`.  Is that something that is possible here?  I think I mentioned this before in a previous standup, but maybe you misunderstood.   Let me know.

2024-08-15 18:26 UTC, seyilonge-ps commented on less/bookmarklets.less
> +    margin: 1.25rem 0;
This was done with an autofix flag. I do remember you mentioned being more particular about fonts being fixed. Thought it was okay as long as fonts were dealt with. I'll revert, and try to see if I can use the `ignore` option to fix only font related ones.

2024-08-26 13:31 UTC, seyilonge-ps commented on less/bookmarklets.less
> +    margin: 1.25rem 0;
These have already been resolved with the recent update using Stylelint's `declaration-property-unit-allowed-list`.

2024-10-09 17:56 UTC, merged