[Work In Progress] Image Gallery Component
PublicisSapient/enable-a11y pull request #234
Opened 2024-12-03 14:26 UTC by psastha-patel

2024-12-03 22:16 UTC, zoltan-dulac reviewed
In general, this is great work.  I especially appreciate how you were able to do all the code walkthrough work without any assistance (it is not exactly the easiest library to work with).

2025-01-06 21:01 UTC, zoltan-dulac reviewed
@psastha-patel Please take a look at the my latest comments.  I would also note that when I am using Safari with Voiceover, the alerts aren't always announced by a screen reader.  Can you take a look as to why?  I'd like to discuss in our next standup.

2025-01-14 20:51 UTC, zoltan-dulac requested changes
I absolutely love this example.  We just need to clean up some things here that I missed in the last code review.  It'll make the information here more understandable.

2025-01-14 20:51 UTC, zoltan-dulac commented on js/modules/image-gallery.js
> +                thumbnail.classList.toggle('active', i === index);
A few thoughts on this:

1. The active state is not always obvious visuslly after I use a keyboard to tab out of the control.  Can we make it more obvious?  Like maybe an underline or something?
2. There should be an `aria-selected="true"` on the item that has been clicked.  This will allow screen readers to know which element is active. You can use that to style the active state described in the first point.

2025-01-14 20:51 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +            <img class="slide" src="images/image-gallery/04-calligraphy.jpg" alt="The image shows a blackboard with white Italic and foundational calligraphy on it.  The text reads 'Things I Hate' fo
Change the alt text by removing "The image shows" from the beginning.  That may be my mistake. Accessibility best practice says not do this, and it effects the UI of the JS you made.

2025-01-14 20:51 UTC, zoltan-dulac commented on js/modules/es4/image-gallery.js
> +                    slideAlert.innerHTML = `Now showing image with ${msg}`;
If this is a gallery with captions, please make sure `slideAlert.innerHTML = `Now showing image with ${msg}. Caption underneath reads: ${caption}.`

2025-01-14 20:51 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +<div id="gallery2" class="gallery" role="group" aria-label="Image Gallery with Caption">
Change the `aria-label` to `Gallery with Calligraphy Photos`, since it accurately describes the contents of the photo gallery.

2025-01-14 20:51 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +            <img src="images/image-gallery/002-product.jpg" alt="Right side view of a miniature Space Invaders arcade machine showing colorful alien graphics and logo on a blue casing. There is a log
You forgot the final single quote at the end of `'Excalibur Electronics Inc.'`

2025-01-14 20:51 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +      "label": "Add aria-label on neccessary tags",
Change this to `Add aria-label to the group container of the photo gallery that describes the contents of the image gallery.`

2025-01-14 20:51 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +      "notes": "This aria-live status will be updated with information for screen reader users on what has changed in the gallery"
`This aria-live region will be updated when a new image is displayed in the gallery that describes what is being shown visually (e.g "Now displaying an image of ....").

2025-01-14 20:51 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +    },
You can remove the "CSS for sr-only" step -- it's described in the page linked in the previous step.

2025-01-14 20:51 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +        "notes": "This function add shows active image in gallery and updates gallery alert message."
I think you can remove this and the code referred.  `display: none` should remove the images not visible from the accessibility tree.

2025-01-14 20:51 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +        "notes": "This will announce what is the image, which is active in the slides using aria-live"
Two notes:

1. Change note to "When the image gallery displays a new image, this is the code that announces the change to screen reader users."
2. Put this step after the step which shows the ARIA live region in the HTML.

2025-01-14 20:51 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +    },
I know you have followed the direction in the other Enable pages, but let's remove all the steps duplicated in the above example and just put in steps that are different.  

At the beginning of the code walkthrough, you can state in the main copy of the page that "All the steps from the previous example should be followed in addition to these additional steps:"

2025-01-14 20:58 UTC, zoltan-dulac reviewed
Forgot to add changes to the copy as well.

2025-01-14 20:58 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +<p>This component is an image carousel designed to showcase images with a smooth scrolling feature. Users can navigate through the images using the next and previous buttons. The active image is high
Let's change this paragraph.

"Image galleries are used in a lot of e-commerce sites to show off the products the site is selling.  Images are a great way for sighted users to know what the product looks like and if it is the one that they want.  But how about blind and partially-sighted users?   They want to know what kind of pictures are in the image gallery as well so they can understand if the product is right for them as well.  The following example is accessible and will announce to screen reader users when a new image is displayed and describe the image via the image's alt text set in the code.

2025-01-14 20:58 UTC, zoltan-dulac commented on content/body/image-gallery.php
> +<p>This example is an image gallery with caption that is designed to showcase images with a smooth scrolling feature.</p>
This is an example of a image gallery where there are captions underneath the image.  Note that in some image galleries on the web, captions don't always describe what is inside the image completely and may just have some additional information (a great example of this is Instagram).  For this reason, it is usually a great idea for screen readers to announce both the image alt text and the caption together when the user elects to display a new image in the gallery.

2025-01-15 16:44 UTC, psastha-patel commented on js/modules/image-gallery.js
> +                thumbnail.classList.toggle('active', i === index);
@zoltan-dulac  Instead of `aria-selected="true"` can we use `aria-pressed="true"`.

2025-01-20 19:42 UTC, zoltan-dulac commented on js/modules/es4/image-gallery.js
> +                }
There should be an `else` to set `aria-pressed` to false otherwise.

2025-01-21 17:14 UTC, zoltan-dulac approved these changes

2025-01-21 17:14 UTC, merged